### ISSUE TITLE
shardingsphere 是否会排期

### ISSUE THREAD

**Issue by zlmkenan** [engineer-365/idea-and-plan#11]
随着数据不断的增多，shardingsphere是否有相关的计划，或者其他类似的相关技术栈

**Comment by qiangyt** [comment]
github有个discussion功能，我放那边去

**Comment by qiangyt** [comment]
https://github.com/orgs/engineer-365/teams/engineers-engineer-365/discussions/1

**Comment by qiangyt** [comment]
已转入discussion。
close。
